version: "3.8"
services:
  api:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/app

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
